#!/bin/bash
VERSION=$(qgis --help 2>&1 | head -n 1 | cut -d'.' -f1)
SCRIPT="$(readlink -f $0)"
DIR="$(dirname $SCRIPT)"
if [ "$VERSION" == "QGIS - 2" ]; then
    source "$DIR/pyqgismac.py"
    python2 "$DIR/main.py" $*
else
    source "$DIR/pyqgis3mac.py"
    python3 "$DIR/main.py" $*
fi

