#!/bin/bash
SCRIPT="$(readlink -f $0)"
DIR="$(dirname $SCRIPT)"
python3 -c "import qgis.core" > /dev/null 2>&1
if [ $? -eq 0 ]; then
    python3 "$DIR/main.py" $*
else
    python2 "$DIR/main.py" $*
fi

