#!/bin/bash
VERSION="QGIS - 2"
if [ -d "/Applications/QGIS3.app" ]; then
    VERSION="QGIS - 3"
fi
SCRIPT="$(readlink $0)"
DIR="$(dirname $SCRIPT)"
if [ "$VERSION" == "QGIS - 2" ]; then
    source "$DIR/pyqgismac.sh"
    python "$DIR/main.py" $*
else
    source "$DIR/pyqgis3mac.sh"
    python3 "$DIR/main.py" $*
fi

